### ISSUE TITLE
onClick Category Label -> Open search

### ISSUE THREAD

**Issue by chomchom02** [diverent2/flagfinder#31] opened 2019-12-29 00:42 UTC
# 💡 feature request

## I would really like the project to

A click listener for the category button on the XYZ page. A click should open the search page with a filter set accordingly. In other words: A click on the button "sexuality" should open the search page with the filter "sexualities" already selected

## Reasons why this change would be good

When I was drunk, it felt intuitive to me. When I was sober, I still thought it was a good idea.

## Other information

![215e2474-4416-451b-9ed8-cc6e2d9d0c33](https://user-images.githubusercontent.com/20092945/71550965-6444dd00-29dc-11ea-8d78-1bbdd7b8a63d.jpg)

**Comment by diverent2** [comment] 2021-06-14 13:58
closed because duplicate of #28

**Closed by diverent2** 2021-06-14 13:58 UTC
Labels: enhancement
